# serverless.yml

service: cartography-service

provider:
  name: aws
  runtime: python3.8
  stage: prod
  region: us-east-2
  memorySize: 1024
  profile: cloudanix-serverless-admin
  apiGateway:
    shouldStartNameWithService: true
  environment:
    CDX_DEFAULT_REGION: ${env:CDX_DEFAULT_REGION}
    CDX_DEFAULT_LOG_LEVEL: ${env:CDX_DEFAULT_LOG_LEVEL}
    CDX_APP_ENV: ${env:CDX_APP_ENV}
    CDX_APP_ASSUME_ROLE_KMS_KEY_ID: ${env:CDX_APP_ASSUME_ROLE_KMS_KEY_ID}
    CDX_APP_ASSUME_ROLE_ACCESS_KEY: ${env:CDX_APP_ASSUME_ROLE_ACCESS_KEY}
    CDX_APP_ASSUME_ROLE_ACCESS_SECRET: ${env:CDX_APP_ASSUME_ROLE_ACCESS_SECRET}
    CDX_APP_NEO4J_URI: ${env:CDX_APP_NEO4J_URI}
    CDX_APP_NEO4J_USER: ${env:CDX_APP_NEO4J_USER}
    CDX_APP_NEO4j_PWD: ${env:CDX_APP_NEO4j_PWD}
  # deploymentBucket:
  #   name: serverless-deployments
  #   serverSideEncryption: AES256

functions:
  cartographyService:
    handler: app.load_cartography
    timeout: 900 # optional, in seconds, default is 30

    role: arn:aws:iam::774118602354:role/cloudanix-lambda-role

    events:
      - sns:
          arn: arn:aws:sns:us-east-2:774118602354:inventory-sync-aws-requests

plugins:
  - serverless-python-requirements
  - serverless-offline
  - serverless-offline-python
  - serverless-offline-sns
  # - serverless-deployment-bucket

custom:
  pythonRequirements:
    dockerizePip: non-linux
  serverless-offline:
    port: 5000
  serverless-offline-sns:
    port: 5002 # a free port for the sns server to run on
    debug: true
  mySnsTopic: "inventory-sync-aws-requests"
  mySnsTopicArn: "arn:aws:sns:us-east-2:774118602354:inventory-sync-aws-requests"
  # deploymentBucket:
  #   versioning: true
  #   accelerate: true
  #   blockPublicAccess: true
  #   tags:
  #     - Key: Environment
  #       Value: production

package:
  exclude:
    - .git/**
    - .github/**
    - .gitignore
    - .DS_Store
    - npm-debug.log
    - .serverless/**
    - .serverless_plugins/**
    - node_modules/**
    - __pycache__/**
    - .mypy_cache/**
    - .pytest_cache/**
    - .python_packages/**
    - .vscode/**
    - venv/**
    - build/**
    - misc/**
    - tests/**
    - cloudformation/**
    - docs/**
    - LICENSE
    - README.md
    - package.json
    - package-lock.json
    - serverless.yml
    - .pre-commit-config.yaml
    - CODE_OF_CONDUCT.md
    - config
    - Dockerfile
    - Makefile
    - NOTICE
    - setup.cfg
    - setup.py
    - setup.sh
    - test-requirements.txt
    - deploy.sh
    - __main__.py
    - requirements.txt
    - .env.aws.development.json
    - .env.aws.production.json
